---
- name: Create Storj Stats Prometheus Directories
  file:
    path: "{{ storj_stats_path }}/prometheus/{{ item }}"
    state: directory
    owner: 65534
    group: 65534
  loop:
    - conf
    - data

- name: Copy Prometheus Config
  template:
    src: "{{ storj_stats_prometheus_config_template }}"
    dest: "{{ storj_stats_path }}/prometheus/conf/prometheus.yml"

- name: Setup Prometheus
  docker_container:
    container_default_behavior: compatibility
    networks_cli_compatible: no
    restart_policy: always
    name: storj-stats-prometheus
    image: prom/prometheus
    memory: 512M
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time={{ storj_stats_prometheus_retention }}'
    mounts:
      - type: bind
        source: "{{ storj_stats_path }}/prometheus/conf"
        target: /etc/prometheus
      - type: bind
        source: "{{ storj_stats_path }}/prometheus/data"
        target: /prometheus
    networks:
      - name: "{{ storj_stats_network_name }}"